Repository auth0/auth0.js, pull requests merged in 2019-06, with the labels that each got.

#947 Update dependencies to fix vulnerabilities
  package.json
  yarn.lock
Labels: CH: Security, tiny

#948 Ignore syntax errors from popups
  src/helper/popup-handler.js
  test/helper/popup-handler.test.js
Labels: CH: Fixed

#949 Add method to patch root user attriutes
  README.md
  src/management/index.js
  test/management/management.test.js
Labels: CH: Added

#952 Fix/check nonce state hs256 tokens
  .babelrc
  .nycrc
  package.json
  rollup.config.js
  src/web-auth/index.js
  test/web-auth/web-auth.test.js
  yarn.lock
Labels: CH: Changed

#950 Release v9.11.0
  CHANGELOG.md
  README.md
  docs/Authentication.html
  docs/Management.html
  docs/WebAuth.html
  docs/authentication_db-connection.js.html
  docs/authentication_index.js.html
  docs/global.html
  docs/index.html
  docs/management_index.js.html
  docs/web-auth_cross-origin-authentication.js.html
  docs/web-auth_hosted-pages.js.html
  docs/web-auth_index.js.html
  docs/web-auth_popup.js.html
  docs/web-auth_redirect.js.html
  package.json
  src/version.js
Labels: tiny

#954 Fix nonce error when id_token doesn't have a nonce
  src/web-auth/index.js
  test/web-auth/web-auth.test.js
Labels: CH: Fixed, tiny

#957 use --trace when uploading to the cdn
  package.json
Labels: tiny

#958 Fix/cdn upload
  yarn.lock
Labels: tiny
