Repository auth0/auth0.js, pull requests merged in 2019-12, with the labels that each got.

#1054 Bugfix for WebExtension
  src/helper/object.js
Labels: tiny

#1057 [CAUTH-239] Add getChallenge method
  src/authentication/index.js
  test/authentication/authentication.test.js
Labels: CH: Added

#1058 Fixed passwordless params priority
  src/authentication/passwordless-authentication.js
  test/authentication/passwordless.test.js
Labels: CH: Fixed, tiny

#1059 [SDK-974] Improved OIDC compliance
  package.json
  src/web-auth/index.js
  test/plugins/cordova.test.js
  test/web-auth/web-auth.test.js
  yarn.lock
Labels: CH: Security, small

#1060 Prepare v9.12.0
  CHANGELOG.md
  README.md
  docs/Authentication.html
  docs/Management.html
  docs/WebAuth.html
  docs/authentication_db-connection.js.html
  docs/authentication_index.js.html
  docs/global.html
  docs/index.html
  docs/management_index.js.html
  docs/web-auth_cross-origin-authentication.js.html
  docs/web-auth_hosted-pages.js.html
  docs/web-auth_index.js.html
  docs/web-auth_popup.js.html
  docs/web-auth_redirect.js.html
  package.json
  src/version.js
Labels: tiny

#1062 Set the default token validation leeway to 60 sec
  src/web-auth/index.js
  test/web-auth/web-auth.test.js
Labels: CH: Fixed, tiny

#1063 Release v9.12.1
  CHANGELOG.md
  README.md
  docs/Authentication.html
  docs/Management.html
  docs/WebAuth.html
  docs/authentication_db-connection.js.html
  docs/authentication_index.js.html
  docs/global.html
  docs/index.html
  docs/management_index.js.html
  docs/web-auth_cross-origin-authentication.js.html
  docs/web-auth_hosted-pages.js.html
  docs/web-auth_index.js.html
  docs/web-auth_popup.js.html
  docs/web-auth_redirect.js.html
  package.json
  src/version.js
Labels: tiny

#1065 Fixes the markdown for checkboxes on the PR and issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tiny
