Repository auth0/auth0.js, pull requests merged in 2020-03, with the labels that each got.

#1085 Fix unit tests by stubbing RSA verification
  test/web-auth/web-auth.test.js
Labels: CH: Fixed, tiny

#1088 Updated JS docs for `user_metadata`
  src/authentication/db-connection.js
Labels: CH: Fixed, documentation

#1084 [SDK-1405] Added support for new 'blocked_reasons' error type
  src/helper/response-handler.js
  test/helper/response-handler.test.js
Labels: CH: Added, small

#1090 [SDK-1405] Release v9.13.0
  CHANGELOG.md
  README.md
  docs/Authentication.html
  docs/Management.html
  docs/WebAuth.html
  docs/authentication_db-connection.js.html
  docs/authentication_index.js.html
  docs/global.html
  docs/index.html
  docs/management_index.js.html
  docs/web-auth_cross-origin-authentication.js.html
  docs/web-auth_hosted-pages.js.html
  docs/web-auth_index.js.html
  docs/web-auth_popup.js.html
  docs/web-auth_redirect.js.html
  package.json
  src/version.js
Labels: tiny

#1091 Update idtoken-verifier dependency
  package.json
  yarn.lock
Labels: CH: Security, tiny
