Repository auth0/auth0.js, pull requests merged in 2020-06, with the labels that each got.

#1112 Regenerated the documentation to show missing callback property
  docs/Authentication.html
  docs/Management.html
  docs/WebAuth.html
  docs/authentication_db-connection.js.html
  docs/authentication_index.js.html
  docs/global.html
  docs/helper_object.js.html
  docs/index.html
  docs/management_index.js.html
  docs/web-auth_cross-origin-authentication.js.html
  docs/web-auth_hosted-pages.js.html
  docs/web-auth_index.js.html
  docs/web-auth_popup.js.html
  docs/web-auth_redirect.js.html
Labels: documentation, tiny

#1113 Bump idtoken-verifier to 2.0.3
  package.json
  yarn.lock
Labels: dependencies, tiny

#1108 Fix IE default redirect url
  src/helper/object.js
Labels: CH: Fixed, tiny

#1116 Release v9.13.3
  CHANGELOG.md
  README.md
  docs/Authentication.html
  docs/Management.html
  docs/WebAuth.html
  docs/authentication_db-connection.js.html
  docs/authentication_index.js.html
  docs/global.html
  docs/helper_object.js.html
  docs/index.html
  docs/management_index.js.html
  docs/web-auth_cross-origin-authentication.js.html
  docs/web-auth_hosted-pages.js.html
  docs/web-auth_index.js.html
  docs/web-auth_popup.js.html
  docs/web-auth_redirect.js.html
  package.json
  src/version.js
Labels: tiny
