Repository auth0/auth0.js, pull requests merged in 2020-04, with the labels that each got.

#1093 Add screen_hint to allowed parameters
  src/helper/parameters-whitelist.js
Labels: CH: Fixed, tiny

#1094 Release v9.13.1
  CHANGELOG.md
  README.md
  docs/Authentication.html
  docs/Management.html
  docs/WebAuth.html
  docs/authentication_db-connection.js.html
  docs/authentication_index.js.html
  docs/global.html
  docs/index.html
  docs/management_index.js.html
  docs/web-auth_cross-origin-authentication.js.html
  docs/web-auth_hosted-pages.js.html
  docs/web-auth_index.js.html
  docs/web-auth_popup.js.html
  docs/web-auth_redirect.js.html
  package.json
  src/version.js
Labels: tiny

#1097 Dependency updates for security advisories
  package.json
  yarn.lock
Labels: CH: Security, dependencies, tiny
