Repository auth0/auth0.js, pull requests merged in 2020-09, with the labels that each got.

#1125 [SDK-1812] Inclusive language updates
  README.md
  src/helper/parameters-whitelist.js
  test/authentication/authentication.test.js
  test/authentication/ro.test.js
  test/helper/object.test.js
  test/web-auth/popup.test.js
Labels: CH: Fixed, small

#1126 [CAUTH-551] add render captcha method
  src/web-auth/captcha.js
  src/web-auth/index.js
  test/web-auth/captcha.test.js
  test/web-auth/web-auth.test.js
Labels: CH: Added, small

#1120 Update superagent dependency to 5.3.1 to get around babel bug
  package.json
  src/helper/request-builder.js
  yarn.lock
Labels: CH: Fixed, dependencies, tiny

#1130 Dependencies and NPM lock file
  .circleci/config.yml
  .gitignore
  package-lock.json
  package.json
  src/web-auth/index.js
  yarn.lock
Labels: CH: Security, dependencies, small

#1132 Use npm instead of yarn in Jenkins CI build
  README.md
  scripts/ci.sh
Labels: tiny
