Repository auth0/auth0.js, pull requests merged in 2021-01, with the labels that each got.

#1144 Allow domain to contain http scheme
  src/authentication/index.js
  test/authentication/authentication.test.js
Labels: CH: Changed

#1147 Release v9.14.1
  CHANGELOG.md
  README.md
  docs/Authentication.html
  docs/Management.html
  docs/WebAuth.html
  docs/authentication_db-connection.js.html
  docs/authentication_index.js.html
  docs/global.html
  docs/helper_object.js.html
  docs/index.html
  docs/management_index.js.html
  docs/web-auth_captcha.js.html
  docs/web-auth_cross-origin-authentication.js.html
  docs/web-auth_hosted-pages.js.html
  docs/web-auth_index.js.html
  docs/web-auth_popup.js.html
  docs/web-auth_redirect.js.html
  package-lock.json
  package.json
  src/version.js
Labels: review:tiny

#1149 Release 9.14.2
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/version.js
Labels: review:tiny

#1153 Add otp to tokenParams
  src/helper/parameters-whitelist.js
Labels: CH: Changed, tiny

#1155 Release v9.14.3
  CHANGELOG.md
  README.md
  docs/Authentication.html
  docs/Management.html
  docs/WebAuth.html
  docs/authentication_db-connection.js.html
  docs/authentication_index.js.html
  docs/global.html
  docs/helper_object.js.html
  docs/index.html
  docs/management_index.js.html
  docs/web-auth_captcha.js.html
  docs/web-auth_cross-origin-authentication.js.html
  docs/web-auth_hosted-pages.js.html
  docs/web-auth_index.js.html
  docs/web-auth_popup.js.html
  docs/web-auth_redirect.js.html
  package.json
  src/version.js
Labels: review:tiny
