Repository auth0/auth0.js, pull requests merged in 2021-04, with the labels that each got.

#1167 Align stalebot config with other SDKs
  .github/stale.yml
Labels: tiny

#1169 Feature/recaptcha enterprise cauth 965
  src/web-auth/captcha.js
  test/web-auth/captcha.test.js
Labels: CH: Added, review:small

#1172 Release v9.16.0
  CHANGELOG.md
  README.md
  docs/Authentication.html
  docs/Management.html
  docs/WebAuth.html
  docs/authentication_db-connection.js.html
  docs/authentication_index.js.html
  docs/global.html
  docs/helper_object.js.html
  docs/index.html
  docs/management_index.js.html
  docs/web-auth_captcha.js.html
  docs/web-auth_cross-origin-authentication.js.html
  docs/web-auth_hosted-pages.js.html
  docs/web-auth_index.js.html
  docs/web-auth_popup.js.html
  docs/web-auth_redirect.js.html
  package.json
  src/version.js
Labels: review:tiny
